@echo off
echo Starting cleanup of temporary files and caches...

:: Delete temporary files
echo Deleting user temp files...
del /q /f "%TEMP%\*.*"
rd /s /q "%TEMP%"

echo Deleting Windows temp files...
del /q /f "C:\Windows\Temp\*.*"
rd /s /q "C:\Windows\Temp"

:: Delete Prefetch files (optional, use with caution)
echo Deleting Prefetch files...
del /q /f "C:\Windows\Prefetch\*.*"
rd /s /q "C:\Windows\Prefetch"

:: Delete launcher caches
echo Deleting Epic Games Launcher cache...
rd /s /q "%LOCALAPPDATA%\EpicGamesLauncher\Saved\webcache"

echo Deleting Steam cache...
rd /s /q "%LOCALAPPDATA%\Steam\htmlcache"

echo Deleting Ubisoft Connect cache...
rd /s /q "%LOCALAPPDATA%\Ubisoft Game Launcher\cache"

echo Deleting GOG Galaxy cache...
rd /s /q "%LOCALAPPDATA%\GOG.com\Galaxy\logs"
rd /s /q "%LOCALAPPDATA%\GOG.com\Galaxy\cache"

:: Delete browser caches
echo Deleting Firefox cache...
rd /s /q "%APPDATA%\Mozilla\Firefox\Profiles\*\cache2"
rd /s /q "%LOCALAPPDATA%\Mozilla\Firefox\Profiles\*\cache2"

echo Deleting Opera cache...
rd /s /q "%APPDATA%\Opera Software\Opera Stable\Cache"

echo Deleting Chrome cache...
rd /s /q "%LOCALAPPDATA%\Google\Chrome\User Data\Default\Cache"

echo Deleting Edge cache...
rd /s /q "%LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Cache"

echo Deleting Brave browser cache...
rd /s /q "%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Default\Cache"

:: Delete additional app caches
echo Deleting Discord cache...
rd /s /q "%APPDATA%\Discord\Cache"
rd /s /q "%LOCALAPPDATA%\Discord\Cache"

echo Deleting Skype cache...
rd /s /q "%APPDATA%\Skype\*"

echo Deleting Teams cache...
rd /s /q "%APPDATA%\Microsoft\Teams\Cache"

echo Deleting Adobe Reader cache...
rd /s /q "%APPDATA%\Adobe\Acrobat\DC\Cache"

echo Deleting Microsoft Office cache...
rd /s /q "%LOCALAPPDATA%\Microsoft\Office\16.0\OfficeFileCache"

echo Deleting Zoom cache...
rd /s /q "%APPDATA%\Zoom\bin"
rd /s /q "%LOCALAPPDATA%\Zoom\*"

echo Deleting Dropbox cache...
rd /s /q "%APPDATA%\Dropbox\cache"
rd /s /q "%LOCALAPPDATA%\Dropbox\cache"

echo Deleting Viber cache...
rd /s /q "%LOCALAPPDATA%\ViberPC\cache"

echo Deleting Telegram cache...
rd /s /q "%APPDATA%\Telegram Desktop\*"

echo Deleting WhatsApp cache...
rd /s /q "%LOCALAPPDATA%\WhatsApp\*"

echo Deleting uTorrent cache...
rd /s /q "%APPDATA%\uTorrent\*"

echo Deleting qBittorrent cache...
rd /s /q "%APPDATA%\qBittorrent\*"

echo Deleting Adobe Photoshop cache...
rd /s /q "%APPDATA%\Adobe\Adobe Photoshop\*"

echo Deleting Epic Games cache...
rd /s /q "%LOCALAPPDATA%\Epic Games\*"

echo Deleting WinRAR cache...
rd /s /q "%APPDATA%\WinRAR\*"

echo Deleting VirtualBox cache...
rd /s /q "%LOCALAPPDATA%\VirtualBox\*"

echo Deleting CCleaner cache...
rd /s /q "%APPDATA%\Piriform\CCleaner\*"

echo Deleting iTunes cache...
rd /s /q "%APPDATA%\Apple Computer\iTunes\*"

echo Deleting Battle.net cache...
rd /s /q "%LOCALAPPDATA%\Blizzard Entertainment\Battle.net\Cache"

echo Deleting Origin cache...
rd /s /q "%LOCALAPPDATA%\Origin\Cache"

echo Deleting Visual Studio cache...
rd /s /q "%LOCALAPPDATA%\Microsoft Visual Studio\Cache\*"

echo Deleting Visual Studio Code cache...
rd /s /q "%APPDATA%\Code\*"

echo Deleting GitHub Desktop cache...
rd /s /q "%APPDATA%\GitHubDesktop\*"

echo Deleting Notepad++ cache...
rd /s /q "%APPDATA%\Notepad++\*"

echo Deleting Adobe Premiere cache...
rd /s /q "%APPDATA%\Adobe\Premiere Pro\*"

echo Deleting Adobe After Effects cache...
rd /s /q "%APPDATA%\Adobe\After Effects\*"

echo Deleting IntelliJ IDEA cache...
rd /s /q "%APPDATA%\JetBrains\IntelliJIdea\*"

echo Deleting PyCharm cache...
rd /s /q "%APPDATA%\JetBrains\PyCharm\*"

echo Deleting 7-Zip cache...
rd /s /q "%APPDATA%\7-Zip\*"

echo Deleting Slack cache...
rd /s /q "%APPDATA%\Slack\Cache"

echo Deleting Microsoft Edge Dev cache...
rd /s /q "%LOCALAPPDATA%\Microsoft\Edge Dev\User Data\Default\Cache"

echo Deleting Mozilla Thunderbird cache...
rd /s /q "%APPDATA%\Thunderbird\Profiles\*\cache2"

echo Deleting Opera GX cache...
rd /s /q "%APPDATA%\Opera Software\Opera GX Stable\Cache"

echo Deleting WhatsApp Desktop cache...
rd /s /q "%LOCALAPPDATA%\WhatsApp\Cache"

echo Deleting uTorrent cache...
rd /s /q "%APPDATA%\uTorrent\*"

echo Deleting BitTorrent cache...
rd /s /q "%APPDATA%\BitTorrent\*"

echo Deleting Adobe Lightroom cache...
rd /s /q "%APPDATA%\Adobe\Lightroom\*"

echo Deleting AVG cache...
rd /s /q "%APPDATA%\AVG\*"

echo Deleting Avast cache...
rd /s /q "%APPDATA%\Avast Software\Avast\*"

echo Deleting Vivaldi browser cache...
rd /s /q "%LOCALAPPDATA%\Vivaldi\User Data\Default\Cache"

echo Deleting AIMP cache...
rd /s /q "%APPDATA%\AIMP\*"

echo Deleting Winamp cache...
rd /s /q "%APPDATA%\Winamp\*"

echo Deleting Audacity cache...
rd /s /q "%APPDATA%\Audacity\*"

echo Deleting Fraps cache...
rd /s /q "%APPDATA%\Fraps\*"

echo Deleting Camtasia cache...
rd /s /q "%APPDATA%\TechSmith\Camtasia Studio\*"

echo Deleting CorelDRAW cache...
rd /s /q "%APPDATA%\Corel\CorelDRAW Graphics Suite\*"

echo Deleting Microsoft OneDrive cache...
rd /s /q "%LOCALAPPDATA%\Microsoft\OneDrive\*"

echo Deleting Spotify cache...
rd /s /q "%APPDATA%\Spotify\*"

echo Deleting Google Earth cache...
rd /s /q "%APPDATA%\Google\Google Earth\*"

echo Deleting SteamVR cache...
rd /s /q "%LOCALAPPDATA%\Steam\config\steamvr"

echo Deleting Origin cache...
rd /s /q "%LOCALAPPDATA%\Electronic Arts\EA Games\*"

echo Deleting Battle.net Launcher cache...
rd /s /q "%APPDATA%\Battle.net\*"

echo Deleting TeamSpeak cache...
rd /s /q "%APPDATA%\TeamSpeak\*"

echo Deleting Epic Games web cache...
rd /s /q "%LOCALAPPDATA%\EpicGamesLauncher\Saved\webcache"

echo Deleting Uplay cache...
rd /s /q "%LOCALAPPDATA%\Ubisoft Game Launcher\cache"

echo Deleting Adobe Acrobat Reader cache...
rd /s /q "%APPDATA%\Adobe\Acrobat\DC\Cache"

echo Deleting Notepad++ cache...
rd /s /q "%APPDATA%\Notepad++\*"

echo Deleting WinZip cache...
rd /s /q "%APPDATA%\WinZip\*"

echo Deleting Dropbox cache...
rd /s /q "%LOCALAPPDATA%\Dropbox\Cache"

echo Deleting Acronis True Image cache...
rd /s /q "%APPDATA%\Acronis\TrueImage\*"

echo Deleting Razer Synapse cache...
rd /s /q "%APPDATA%\Razer\Synapse\*"

echo Deleting Corsair iCUE cache...
rd /s /q "%APPDATA%\Corsair\iCUE\*"

echo Deleting MSI Afterburner cache...
rd /s /q "%APPDATA%\MSI Afterburner\*"

echo Deleting Logitech G Hub cache...
rd /s /q "%APPDATA%\LGHUB\*"

echo Deleting Discord voice cache...
rd /s /q "%APPDATA%\Discord\voice"

:: Completion
echo Cleanup completed! All specified caches and temporary files have been deleted.
pause
